<?php

namespace common\onecms;

use common\models\Review;
use yii\base\Widget;

class FrontReviewWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = $this->getData();
        return $this->render('FrontReviewWidget', [
            'nodes' => $nodes,
        ]);
    }

    public static function getData()
    {
        $reviewModel = new Review();
        $reviewData = $reviewModel->find()->limit(12)->all();
        return $reviewData;
    }
}