<?php

namespace common\onecms;

use common\models\Post;
use yii\base\Widget;

class FrontPostWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = $this->getData();
        return $this->render('FrontPostWidget', [
            'nodes' => $nodes,
        ]);
    }

    public static function getData()
    {
        $postModel = new Post();
        $postData = $postModel->find()->limit(5)->all();
        return $postData;
    }
}