<?php

namespace common\onecms;

use common\models\ReviewCategory;
use yii\base\Widget;

class NavWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $categories = $this->build();
        return $this->render('NavWidget', [
            'categories' => $categories,
        ]);
    }

    public static function build()
    {
        $categoriesModel = new ReviewCategory();
        $categoriesData = $categoriesModel->find()->addOrderBy(['tree' => SORT_ASC])->addOrderBy(['lft' => SORT_ASC])->all();

        return $categoriesData;
    }
}