<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Depth' => '',
    'ID' => '',
    'Layouts' => '',
    'Lft' => '',
    'Link' => '',
    'Meta Params' => '',
    'Parent ID' => '',
    'Rgt' => '',
    'Tree' => '',
    'Update Category Post' => '',
    'Update Category Product' => '',
    'Update Page' => '',
    'Views' => '',
    'Advertisings' => 'Quảng cáo',
    'Are you sure you want to delete this item?' => 'Bạn có chắc chắn muốn xóa?',
    'Category ID' => 'Danh mục',
    'Category Posts' => 'Danh mục',
    'Category Products' => 'Danh mục',
    'Content' => 'Nội dung',
    'Create' => 'Thêm mới',
    'Create Advertising' => 'Thêm mới',
    'Create Category Post' => 'Thêm mới',
    'Create Category Product' => 'Thêm mới',
    'Create Page' => 'Thêm mới',
    'Create Post' => 'Thêm mới',
    'Create Product' => 'Thêm mới',
    'Create Setting' => 'Thêm mới',
    'Created At' => 'Ngày tạo',
    'Created By' => 'Tạo bởi',
    'Delete' => 'Xóa',
    'Discount' => 'Giảm giá (%)',
    'End Date' => 'Ngày kết thúc',
    'Image' => 'Hình ảnh',
    'Images' => 'Thư viện ảnh',
    'Meta Description' => 'SEO - Mô tả',
    'Meta Key' => 'Setting - Key',
    'Meta Keywords' => 'SEO - Từ khóa',
    'Meta Title' => 'SEO - Tiêu đề',
    'Meta Value' => 'Setting - Value',
    'Pages' => 'Trang cố định',
    'Position' => 'Vị trí',
    'Posts' => 'Nội dung',
    'Price' => 'Giá',
    'Products' => 'Sản phẩm',
    'Published' => 'Trạng thái',
    'Quantity' => 'Số lượng',
    'Reset' => 'Làm lại',
    'Search' => 'Tìm kiếm',
    'Settings' => 'Cấu hình',
    'Sku' => 'Mã sản phẩm (SKU)',
    'Slug' => 'Slug - Đường dẫn thân thiện',
    'Start Date' => 'Ngày bắt đầu',
    'Summary' => 'Mô tả ngắn',
    'Title' => 'Tiêu đề',
    'Update' => 'Cập nhật',
    'Update Advertising' => 'Cập nhật',
    'Update Post' => 'Cập nhật',
    'Update Product' => 'Cập nhật',
    'Update Setting' => 'Cập nhật',
    'Updated At' => 'Cập nhật ngày',
    'Updated By' => 'Cập nhật bởi',
    'Specification' => 'Thông số kỹ thuật',
];
